# A sample Guardfile
# More info at http://github.com/guard/guard#readme

guard 'nanoc', :rubygems => true do
  watch('^config.yaml')
  watch('^Rules')
  watch('^layouts\/')
  watch('^content\/')
end
